# mamba env create -f environment.dev.yml --force
name: screen-checker
channels: [conda-forge]
dependencies:
  - opencv=4.5 # https://youtrack.jetbrains.com/issue/PY-35691/Code-completion-doesnt-work-for-cv2-module
  # dev
  - black
  - pytest-cov
  - jupyter
  - matplotlib
