name: check

on:
  push:
  pull_request:

env:
  PYTHONPATH: ../src
  TESSDATA_PREFIX: ./

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: tests
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@v12
        with:
          environment-file: "environment.dev.yml"
      - run: sudo apt-get install -y tesseract-ocr
      - run: wget https://github.com/adrianlazaro8/Tesseract_sevenSegmentsLetsGoDigital/raw/master/Trained%20data/lets.traineddata
      - run: pytest --cov=../ --cov-report xml
      - uses: codecov/codecov-action@v3
